# nome = input('Digite o nome completo: ')
# print(nome.upper())
# print(nome.lower())
# print('Sem considerar os espaços seu nome tem: {} letras.'.format(len(''.join(nome.split()))))
# print('Seu primeiro nome tem: {} letras'.format(len(nome.split()[0])))

# divisao = nome.split()
# print('Seu primeiro nome tem: {} letras'.format(len(divisao[0])))

nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maíusculas é: {}'.format(nome.upper()))
print('Seu nome em minúsculas é: {}'.format(nome.lower()))
print('Seu nome tem ao todo: {} letras'.format(len(nome) - nome.count(' ')))
# print('Seu primeiro nome tem {} letras: '.format(nome.find(' ')))
separa =  nome.split()
print('Seu primeiro nome é: {} e ele tem: {} letras'.format(separa[0], len(separa[0])))